trigger:
- master

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'rsuomibotti_azure_palvelin'
    sourceFolder: 'commands/'
    contents: '**'
    targetFolder: '/home/winaj/.saxo/commands'

    - task: SSH@0
      inputs:
        sshEndpoint: 'rsuomibotti_azure_palvelin'
        runOptions: 'commands'
        commands: 'chmod +x /home/winaj/.saxo/commands/*'