trigger:
- master

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'rsuomibotti'
    sourceFolder: 'commands/'
    contents: '**'
    targetFolder: '/home/winaj/.saxo/commands'

- task: SSH@0
  inputs:
    sshEndpoint: 'rsuomibotti'
    runOptions: 'commands'
    commands: 'chmod +x /home/winaj/.saxo/commands/*'