#!/usr/bin/env python3

import os.path
import time
import saxo

@saxo.command(authorised=True)
def addquote(arg):
    if arg:
        with saxo.database() as db:
            now = int(time.time())
            channel = saxo.env("sender")
            db["saxo_quote"].insert((now, channel, arg))
            return "Quote saved"
