#!/usr/bin/env python3

import saxo
import random

secure_random = random.SystemRandom()

vastaukset = [
  'Aika varmasti',
  'Se on päätetty niin',
  'Ilman epäilystäkään',
  'Kyllä - ihan varmasti',
  'Voit luottaa siihen',
  'Näkisin, että näin se on',
  'Todennäköisesti',
  'Ennuste on hyvä',
  'Kyllä',
  'Merkit viittaavat siihen, että kyllä',
  'Vastaus epäselvä, kokeiles uudestaan',
  'Kysy myöhemmin uudestaan',
  'Ei passaa kertoa just nyt',
  'En osaa just nyt ennustaa',
  'Keskityppäs ja yritä uudestaan',
  'En luottais',
  'Vastaukseni on: ei',
  'Lähteeni sanovat, että ei',
  'Ennuste on huono',
  'Epäilen vahvasti'
  ]
  
@saxo.pipe
def kasipallo(arg):
  return secure_random.choice(vastaukset)
