#!/usr/bin/env python3

import urllib.parse
import saxo

@saxo.pipe
def weather(arg):
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://services.nonceword.org/r/weather/" + arg)
    return page["text"]
