#!/usr/bin/env python3

import requests
import saxo
import random
from bs4 import BeautifulSoup

@saxo.pipe
def ud(arg):
  if arg:
    word = arg
    r = requests.get("http://www.urbandictionary.com/define.php?term={}".format(word))
    soup = BeautifulSoup(r.content)

    meaning = soup.find("div",attrs={"class":"meaning"})
    if meaning:
      return meaning.text
    
    return "Sorry, we couldn't find: " + arg
